sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse --short HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project scaling-octo-garbanzo
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials scaling-octo-garbanzo
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t lbakerjs/scaling-octo-garbanzo-client-dev -f ./client/Dockerfile.dev ./client
  - rm service-account.json

script:
  - docker run -e CI=true lbakerjs/scaling-octo-garbanzo-client-dev npm run test


deploy:
  on:
    branch: master
  provider: script
  script: bash ./deploy.sh
